// skepickleCharacterSuite
//   Rules library: UA

// Purpose: Provide the 3.5e UA rules to be used by skepickleCharacterSuite.
// ANSI Text Generator: http://patorjk.com/software/taag/#p=display&f=ANSI%20Shadow

var skepickleCharacterSuite_UA = skepickleCharacterSuite_UA || (function skepickleCharacterSuiteImp_UA() {

  // SECTION_ANCHOR
  // ██████╗    ██╗   ██████╗     ██████╗    ███████╗    ████████╗ █████╗ ██████╗ ██╗     ███████╗███████╗
  // ██╔══██╗   ██║   ██╔══██╗    ╚════██╗   ██╔════╝    ╚══██╔══╝██╔══██╗██╔══██╗██║     ██╔════╝██╔════╝
  // ██║  ██║████████╗██║  ██║     █████╔╝   ███████╗       ██║   ███████║██████╔╝██║     █████╗  ███████╗
  // ██║  ██║██╔═██╔═╝██║  ██║     ╚═══██╗   ╚════██║       ██║   ██╔══██║██╔══██╗██║     ██╔══╝  ╚════██║
  // ██████╔╝██████║  ██████╔╝    ██████╔╝██╗███████║       ██║   ██║  ██║██████╔╝███████╗███████╗███████║
  // ╚═════╝ ╚═════╝  ╚═════╝     ╚═════╝ ╚═╝╚══════╝       ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚══════╝╚══════╝╚══════╝

  let source_text_UA = {
    spells: {
      'acid arrow':                      { recharge: 'General' },
      'acid fog':                        { recharge: 'General' },
      'acid splash':                     { recharge: 'General' },
      'aid':                             { recharge: '5 minutes' },
      'air walk':                        { recharge: '1 hour' },
      'alarm':                           { recharge: '4 hours' },
      'align weapon':                    { recharge: '5 minutes' },
      'alter self':                      { recharge: '4 hours' },
      'analyze dweomer':                 { recharge: 'General' },
      'animal growth':                   { recharge: 'General' },
      'animal messenger':                { recharge: '6 hours' },
      'animal shapes':                   { recharge: '24 hours' },
      'animal trance':                   { recharge: 'General' },
      'animate dead':                    { recharge: 'General' },
      'animate objects':                 { recharge: 'General' },
      'animate plants':                  { recharge: 'General' },
      'animate rope':                    { recharge: 'General' },
      'antilife shell':                  { recharge: 'General' },
      'antimagic field':                 { recharge: 'General' },
      'antipathy':                       { recharge: 'General' },
      'antiplant shell':                 { recharge: 'General' },
      'arcane eye':                      { recharge: 'General' },
      'arcane lock':                     { recharge: '1 hour' },
      'arcane mark':                     { recharge: 'General' },
      'arcane sight':                    { recharge: '30 minutes' },
      'armor of darkness':               { recharge: 'General' },
      'astral projection':               { recharge: 'General' },
      'atonement':                       { recharge: 'General' },
      'augury':                          { recharge: '6 hours' },
      'awaken':                          { recharge: 'General' },
      'baleful polymorph':               { recharge: 'General' },
      'bane':                            { recharge: 'General' },
      'banishment':                      { recharge: 'General' },
      'barkskin':                        { recharge: '1 hour' },
      'bear\'s endurance':               { recharge: '5 minutes' },
      'bestow curse':                    { recharge: 'General' },
      'binding':                         { recharge: 'General' },
      'black tentacles':                 { recharge: 'General' },
      'blacklight':                      { recharge: 'General' },
      'blade barrier':                   { recharge: 'General' },
      'blasphemy':                       { recharge: 'General' },
      'bless':                           { recharge: '30 minutes' },
      'bless water':                     { recharge: 'General' },
      'bless weapon':                    { recharge: '5 minutes' },
      'blight':                          { recharge: 'General' },
      'blindness/deafness':              { recharge: 'General' },
      'blink':                           { recharge: 'General' },
      'blur':                            { recharge: '5 minutes' },
      'bolt of glory':                   { recharge: 'General' },
      'bolts of bedevilment':            { recharge: 'General' },
      'brain spider':                    { recharge: '1 hour' },
      'break enchantment':               { recharge: '1 hour' },
      'bull\'s strength':                { recharge: '5 minutes' },
      'burning hands':                   { recharge: 'General' },
      'call lightning':                  { recharge: 'General' },
      'call lightning storm':            { recharge: 'General' },
      'calm animals':                    { recharge: 'General' },
      'calm emotions':                   { recharge: 'General' },
      'cat\'s grace':                    { recharge: '5 minutes' },
      'cause fear':                      { recharge: 'General' },
      'chain lightning':                 { recharge: 'General' },
      'changestaff':                     { recharge: '6 hours' },
      'chaos hammer':                    { recharge: 'General' },
      'charm animal':                    { recharge: '1 hour' },
      'charm monster':                   { recharge: '1 hour' },
      'charm person':                    { recharge: '1 hour' },
      'chill metal':                     { recharge: 'General' },
      'chill touch':                     { recharge: 'General' },
      'circle of death':                 { recharge: 'General' },
      'clenched fist':                   { recharge: 'General' },
      'clairaudience/clairvoyance':      { recharge: 'General' },
      'cloak of chaos':                  { recharge: 'General' },
      'clone':                           { recharge: 'General' },
      'cloudkill':                       { recharge: 'General' },
      'color spray':                     { recharge: 'General' },
      'command':                         { recharge: 'General' },
      'command plants':                  { recharge: '1 hour' },
      'command undead':                  { recharge: '1 hour' },
      'commune':                         { recharge: '6 hours' },
      'commune with nature':             { recharge: '6 hours' },
      'comprehend languages':            { recharge: '4 hours' },
      'cone of cold':                    { recharge: 'General' },
      'confusion':                       { recharge: 'General' },
      'consecrate':                      { recharge: '30 minutes' },
      'contact other plane':             { recharge: '6 hours' },
      'contagion':                       { recharge: 'General' },
      'contingency':                     { recharge: 'General' },
      'continual flame':                 { recharge: 'General' },
      'control plants':                  { recharge: '30 minutes' },
      'control undead':                  { recharge: '30 minutes' },
      'control water':                   { recharge: '1 hour' },
      'control weather':                 { recharge: 'General' },
      'control winds':                   { recharge: '4 hours' },
      'create food and water':           { recharge: '24 hours' },
      'create greater undead':           { recharge: 'General' },
      'create undead':                   { recharge: 'General' },
      'create water':                    { recharge: '30 minutes' },
      'creeping doom':                   { recharge: 'General' },
      'crown of glory':                  { recharge: 'General' },
      'crushing despair':                { recharge: 'General' },
      'crushing hand':                   { recharge: 'General' },
      'cure critical wounds':            { recharge: 'General' },
      'cure light wounds':               { recharge: 'General' },
      'cure minor wounds':               { recharge: 'General' },
      'cure moderate wounds':            { recharge: 'General' },
      'cure serious wounds':             { recharge: 'General' },
      'curse water':                     { recharge: 'General' },
      'dancing lights':                  { recharge: 'General' },
      'darkness':                        { recharge: '4 hours' },
      'darkvision':                      { recharge: '6 hours' },
      'daylight':                        { recharge: '4 hours' },
      'daze':                            { recharge: 'General' },
      'daze monster':                    { recharge: 'General' },
      'death knell':                     { recharge: 'General' },
      'death ward':                      { recharge: '5 minutes' },
      'deathwatch':                      { recharge: '4 hours' },
      'deep slumber':                    { recharge: 'General' },
      'deeper darkness':                 { recharge: '24 hours' },
      'delay poison':                    { recharge: '6 hours' },
      'delayed blast fireball':          { recharge: 'General' },
      'demand':                          { recharge: '30 minutes' },
      'desecrate':                       { recharge: '30 minutes' },
      'destruction':                     { recharge: 'General' },
      'detect animals or plants':        { recharge: 'General' },
      'detect chaos':                    { recharge: 'General' },
      'detect evil':                     { recharge: 'General' },
      'detect good':                     { recharge: 'General' },
      'detect law':                      { recharge: 'General' },
      'detect magic':                    { recharge: 'General' },
      'detect poison':                   { recharge: '5 minutes' },
      'detect scrying':                  { recharge: 'General' },
      'detect secret doors':             { recharge: 'General' },
      'detect snares and pits':          { recharge: 'General' },
      'detect thoughts':                 { recharge: 'General' },
      'detect undead':                   { recharge: 'General' },
      'dictum':                          { recharge: 'General' },
      'dimension door':                  { recharge: 'General' },
      'dimensional anchor':              { recharge: 'General' },
      'dimensional lock':                { recharge: '24 hours' },
      'diminish plants':                 { recharge: '4 hours' },
      'discern lies':                    { recharge: '6 hours' },
      'discern location':                { recharge: '6 hours' },
      'disguise self':                   { recharge: '4 hours' },
      'disintegrate':                    { recharge: 'General' },
      'disjunction':                     { recharge: 'General' },
      'dismissal':                       { recharge: 'General' },
      'dispel chaos':                    { recharge: 'General' },
      'dispel evil':                     { recharge: 'General' },
      'dispel good':                     { recharge: 'General' },
      'dispel law':                      { recharge: 'General' },
      'dispel magic':                    { recharge: 'General' },
      'displacement':                    { recharge: 'General' },
      'disrupt undead':                  { recharge: 'General' },
      'disrupting weapon':               { recharge: '5 minutes' },
      'divination':                      { recharge: '6 hours' },
      'divine favor':                    { recharge: '5 minutes' },
      'divine power':                    { recharge: '5 minutes' },
      'dominate animal':                 { recharge: 'General' },
      'dominate monster':                { recharge: '12 hours' },
      'dominate person':                 { recharge: '12 hours' },
      'doom':                            { recharge: 'General' },
      'dream':                           { recharge: 'General' },
      'dweomer of transference':         { recharge: '1 hour' },
      'eagle\'s splendor':               { recharge: '5 minutes' },
      'earthquake':                      { recharge: '12 hours' },
      'elemental swarm':                 { recharge: '1 hour' },
      'endure elements':                 { recharge: '6 hours' },
      'energy drain':                    { recharge: 'General' },
      'enervation':                      { recharge: 'General' },
      'enlarge person':                  { recharge: '5 minutes' },
      'entangle':                        { recharge: 'General' },
      'enthrall':                        { recharge: 'General' },
      'entropic shield':                 { recharge: '30 minutes' },
      'erase':                           { recharge: 'General' },
      'ethereal jaunt':                  { recharge: '30 minutes' },
      'etherealness':                    { recharge: '30 minutes' },
      'expeditious retreat':             { recharge: '30 minutes' },
      'explosive runes':                 { recharge: '24 hours' },
      'eyebite':                         { recharge: 'General' },
      'fabricate':                       { recharge: '4 hours' },
      'faerie fire':                     { recharge: 'General' },
      'false life':                      { recharge: '30 minutes' },
      'false vision':                    { recharge: '24 hours' },
      'fear':                            { recharge: 'General' },
      'feather fall':                    { recharge: 'General' },
      'feeblemind':                      { recharge: 'General' },
      'find the path':                   { recharge: '4 hours' },
      'find traps':                      { recharge: '30 minutes' },
      'finger of death':                 { recharge: 'General' },
      'fire seeds':                      { recharge: '1 hour' },
      'fire shield':                     { recharge: 'General' },
      'fire storm':                      { recharge: 'General' },
      'fire trap':                       { recharge: '24 hours' },
      'fireball':                        { recharge: 'General' },
      'flame arrow':                     { recharge: 'General' },
      'flame blade':                     { recharge: 'General' },
      'flame strike':                    { recharge: 'General' },
      'flaming sphere':                  { recharge: 'General' },
      'flare':                           { recharge: 'General' },
      'flesh to stone':                  { recharge: 'General' },
      'floating disk':                   { recharge: '6 hours' },
      'fly':                             { recharge: '5 minutes' },
      'fog cloud':                       { recharge: 'General' },
      'forbiddance':                     { recharge: 'General' },
      'forcecage':                       { recharge: 'General' },
      'forceful hand':                   { recharge: 'General' },
      'foresight':                       { recharge: '1 hour' },
      'fox\'s cunning':                  { recharge: '5 minutes' },
      'freedom':                         { recharge: 'General' },
      'freedom of movement':             { recharge: '1 hour' },
      'freezing sphere':                 { recharge: 'General' },
      'gaseous form':                    { recharge: '5 minutes' },
      'gate':                            { recharge: 'General' },
      'geas/quest':                      { recharge: 'General' },
      'genesis':                         { recharge: 'General' },
      'gentle repose':                   { recharge: 'General' },
      'ghost sound':                     { recharge: 'General' },
      'ghoul touch':                     { recharge: 'General' },
      'giant vermin':                    { recharge: '30 minutes' },
      'glibness':                        { recharge: '4 hours' },
      'glitterdust':                     { recharge: 'General' },
      'globe of invulnerability':        { recharge: 'General' },
      'glossolalia':                     { recharge: 'General' },
      'glyph of warding':                { recharge: 'General' },
      'good hope':                       { recharge: '30 minutes' },
      'goodberry':                       { recharge: '6 hours' },
      'grasping hand':                   { recharge: 'General' },
      'grease':                          { recharge: 'General' },
      'greater arcane sight':            { recharge: '30 minutes' },
      'greater command':                 { recharge: 'General' },
      'greater dispel magic':            { recharge: 'General' },
      'greater glyph of warding':        { recharge: 'General' },
      'greater heroism':                 { recharge: '30 minutes' },
      'greater invisibility':            { recharge: 'General' },
      'greater magic fang':              { recharge: '6 hours' },
      'greater magic weapon':            { recharge: '6 hours' },
      'greater planar ally':             { recharge: '24 hours' },
      'greater planar binding':          { recharge: '24 hours' },
      'greater prying eyes':             { recharge: 'General' },
      'greater psychic turmoil':         { recharge: 'General' },
      'greater restoration':             { recharge: 'General' },
      'greater scrying':                 { recharge: '6 hours' },
      'greater shadow conjuration':      { recharge: 'General' },
      'greater shadow evocation':        { recharge: 'General' },
      'greater shout':                   { recharge: 'General' },
      'greater spell immunity':          { recharge: '1 hour' },
      'greater status':                  { recharge: 'General' },
      'greater teleport':                { recharge: '4 hours' },
      'guards and wards':                { recharge: '24 hours' },
      'guidance':                        { recharge: '5 minutes' },
      'gust of wind':                    { recharge: 'General' },
      'hallow':                          { recharge: 'General' },
      'hallucinatory terrain':           { recharge: '6 hours' },
      'halt undead':                     { recharge: 'General' },
      'hardening':                       { recharge: 'General' },
      'harm':                            { recharge: 'General' },
      'haste':                           { recharge: 'General' },
      'heal':                            { recharge: 'General' },
      'heal mount':                      { recharge: 'General' },
      'heat metal':                      { recharge: 'General' },
      'helping hand':                    { recharge: '6 hour' },
      'heroes\' feast':                  { recharge: '24 hours' },
      'heroism':                         { recharge: '1 hour' },
      'hide from animals':               { recharge: '4 hours' },
      'hide from undead':                { recharge: '4 hours' },
      'hideous laughter':                { recharge: 'General' },
      'hold animal':                     { recharge: 'General' },
      'hold monster':                    { recharge: 'General' },
      'hold person':                     { recharge: 'General' },
      'hold portal':                     { recharge: 'General' },
      'holy aura':                       { recharge: 'General' },
      'holy smite':                      { recharge: 'General' },
      'holy sword':                      { recharge: 'General' },
      'holy word':                       { recharge: 'General' },
      'horrid wilting':                  { recharge: 'General' },
      'hypnotic pattern':                { recharge: 'General' },
      'hypnotism':                       { recharge: 'General' },
      'ice storm':                       { recharge: 'General' },
      'identify':                        { recharge: 'General' },
      'illusory script':                 { recharge: 'General' },
      'illusory wall':                   { recharge: '24 hours' },
      'imbue with spell ability':        { recharge: 'General' },
      'implosion':                       { recharge: 'General' },
      'imprisonment':                    { recharge: 'General' },
      'incendiary cloud':                { recharge: 'General' },
      'inflict critical wounds':         { recharge: 'General' },
      'inflict light wounds':            { recharge: 'General' },
      'inflict minor wounds':            { recharge: 'General' },
      'inflict moderate wounds':         { recharge: 'General' },
      'inflict serious wounds':          { recharge: 'General' },
      'insanity':                        { recharge: 'General' },
      'insect plague':                   { recharge: '5 minutes' },
      'instant summons':                 { recharge: 'General' },
      'interposing hand':                { recharge: 'General' },
      'invisibility':                    { recharge: '5 minutes' },
      'invisibility purge':              { recharge: '30 minutes' },
      'invisibility sphere':             { recharge: 'General' },
      'iron body':                       { recharge: '30 minutes' },
      'ironwood':                        { recharge: '12 hours' },
      'irresistible dance':              { recharge: 'General' },
      'jump':                            { recharge: '5 minutes' },
      'keen edge':                       { recharge: '1 hour' },
      'knock':                           { recharge: '5 minutes' },
      'know direction':                  { recharge: 'General' },
      'legend lore':                     { recharge: 'General' },
      'lesser confusion':                { recharge: 'General' },
      'lesser geas':                     { recharge: 'General' },
      'lesser globe of invulnerability': { recharge: 'General' },
      'lesser planar ally':              { recharge: '24 hours' },
      'lesser planar binding':           { recharge: '24 hours' },
      'lesser restoration':              { recharge: 'General' },
      'lesser telepathic bond':          { recharge: '1 hour' },
      'levitate':                        { recharge: '5 minutes' },
      'light':                           { recharge: '1 hour' },
      'lightning bolt':                  { recharge: 'General' },
      'limited wish':                    { recharge: 'General' },
      'liveoak':                         { recharge: '12 hours' },
      'locate creature':                 { recharge: '4 hours' },
      'locate object':                   { recharge: '30 minutes' },
      'longstrider':                     { recharge: '24 hours' },
      'lullaby':                         { recharge: 'General' },
      'maddening scream':                { recharge: 'General' },
      'mage armor':                      { recharge: '6 hours' },
      'mage hand':                       { recharge: 'General' },
      'mage\'s disjunction':             { recharge: 'General' },
      'mage\'s faithful hound':          { recharge: '6 hours' },
      'mage\'s lucubration':             { recharge: 'Prohibited' },
      'mage\'s magnificent mansion':     { recharge: '6 hours' },
      'mage\'s private sanctum':         { recharge: '24 hours' },
      'mage\'s sword':                   { recharge: 'General' },
      'magic aura':                      { recharge: '24 hours' },
      'magic circle against chaos':      { recharge: '4 hours' },
      'magic circle against evil':       { recharge: '4 hours' },
      'magic circle against good':       { recharge: '4 hours' },
      'magic circle against law':        { recharge: '4 hours' },
      'magic fang':                      { recharge: '5 minutes' },
      'magic jar':                       { recharge: 'General' },
      'magic missile':                   { recharge: 'General' },
      'magic mouth':                     { recharge: '24 hours' },
      'magic stone':                     { recharge: '5 minutes' },
      'magic vestment':                  { recharge: '6 hours' },
      'magic weapon':                    { recharge: '5 minutes' },
      'major creation':                  { recharge: 'General' },
      'major image':                     { recharge: 'General' },
      'make whole':                      { recharge: '6 hours' },
      'mark of justice':                 { recharge: 'General' },
      'mass bear\'s endurance':          { recharge: '30 minutes' },
      'mass bull\'s strength':           { recharge: '30 minutes' },
      'mass cat\'s grace':               { recharge: '30 minutes' },
      'mass charm monster':              { recharge: '1 hour' },
      'mass cure critical wounds':       { recharge: 'General' },
      'mass cure light wounds':          { recharge: 'General' },
      'mass cure moderate wounds':       { recharge: 'General' },
      'mass cure serious wounds':        { recharge: 'General' },
      'mass eagle\'s splendor':          { recharge: '30 minutes' },
      'mass enlarge person':             { recharge: '30 minutes' },
      'mass fox\'s cunning':             { recharge: '30 minutes' },
      'mass heal':                       { recharge: 'General' },
      'mass hold monster':               { recharge: 'General' },
      'mass hold person':                { recharge: 'General' },
      'mass inflict critical wounds':    { recharge: 'General' },
      'mass inflict light wounds':       { recharge: 'General' },
      'mass inflict moderate wounds':    { recharge: 'General' },
      'mass inflict serious wounds':     { recharge: 'General' },
      'mass invisibility':               { recharge: '30 minutes' },
      'mass owl\'s wisdom':              { recharge: '30 minutes' },
      'mass reduce person':              { recharge: '30 minutes' },
      'mass suggestion':                 { recharge: '30 minutes' },
      'maze':                            { recharge: 'General' },
      'meld into stone':                 { recharge: '4 hours' },
      'mending':                         { recharge: '6 hours' },
      'mental pinnacle':                 { recharge: 'General' },
      'message':                         { recharge: 'General' },
      'meteor swarm':                    { recharge: 'General' },
      'mind blank':                      { recharge: '12 hours' },
      'mind fog':                        { recharge: '6 hours' },
      'minor creation':                  { recharge: '6 hours' },
      'minor image':                     { recharge: '12 hours' },
      'miracle':                         { recharge: 'General' },
      'mirage arcana':                   { recharge: 'General' },
      'mirror image':                    { recharge: '30 minutes' },
      'misdirection':                    { recharge: '6 hours' },
      'mislead':                         { recharge: 'General' },
      'mnemonic enhancer':               { recharge: 'General' },
      'modify memory':                   { recharge: 'General' },
      'moment of prescience':            { recahrge: '6 hours' },
      'mount':                           { recharge: '6 hours' },
      'move earth':                      { recharge: '1 hour' },
      'neutralize poison':               { recharge: '1 hour' },
      'nightmare':                       { recharge: 'General' },
      'nondetection':                    { recharge: '6 hours' },
      'obscure object':                  { recharge: '24 hours' },
      'obscuring mist':                  { recharge: 'General' },
      'open/close':                      { recharge: 'General' },
      'order\'s wrath':                  { recharge: 'General' },
      'overland flight':                 { recharge: '6 hours' },
      'owl\'s wisdom':                   { recharge: '5 minutes' },
      'pass without trace':              { recharge: '6 hours' },
      'passwall':                        { recharge: '6 hours' },
      'permanency':                      { recharge: 'General' },
      'permanent image':                 { recharge: '24 hours' },
      'persistent image':                { recharge: '30 minutes' },
      'phantasmal killer':               { recharge: 'General' },
      'phantom steed':                   { recharge: '6 hours' },
      'phantom trap':                    { recharge: '24 hours' },
      'phase door':                      { recharge: '12 hours' },
      'planar ally':                     { recharge: '24 hours' },
      'planar binding':                  { recharge: '24 hours' },
      'plane shift':                     { recharge: 'General' },
      'plant growth':                    { recharge: '24 hours' },
      'poison':                          { recharge: 'General' },
      'polar ray':                       { recharge: 'General' },
      'polymorph':                       { recharge: '30 minutes' },
      'polymorph any object':            { recharge: '12 hours' },
      'power word blind':                { recharge: 'General' },
      'power word kill':                 { recharge: 'General' },
      'power word stun':                 { recharge: 'General' },
      'prayer':                          { recharge: '5 minutes' },
      'prestidigitation':                { recharge: 'General' },
      'prismatic sphere':                { recharge: 'General' },
      'prismatic spray':                 { recharge: 'General' },
      'prismatic wall':                  { recharge: 'General' },
      'probe thoughts':                  { recharge: 'General' },
      'produce flame':                   { recharge: 'General' },
      'programmed image':                { recharge: '12 hours' },
      'project image':                   { recharge: 'General' },
      'protection from arrows':          { recharge: '6 hours' },
      'protection from chaos':           { recharge: '5 minutes' },
      'protection from energy':          { recharge: '1 hour' },
      'protection from evil':            { recharge: '5 minutes' },
      'protection from good':            { recharge: '5 minutes' },
      'protection from law':             { recharge: '5 minutes' },
      'protection from spells':          { recharge: '4 hours' },
      'prying eyes':                     { recharge: 'General' },
      'psychic turmoil':                 { recharge: 'General' },
      'purify food and drink':           { recharge: '5 minutes' },
      'pyrotechnics':                    { recharge: 'General' },
      'quench':                          { recharge: 'General' },
      'rage':                            { recharge: '5 minutes' },
      'rainbow pattern':                 { recharge: 'General' },
      'raise dead':                      { recharge: 'General' },
      'ray of enfeeblement':             { recharge: 'General' },
      'ray of exhaustion':               { recharge: 'General' },
      'ray of frost':                    { recharge: 'General' },
      'read magic':                      { recharge: 'General' },
      'reduce animal':                   { recharge: '6 hours' },
      'reduce person':                   { recharge: '30 minutes' },
      'refuge':                          { recharge: 'General' },
      'regenerate':                      { recharge: 'General' },
      'reincarnate':                     { recharge: 'General' },
      'remove blindness/deafness':       { recharge: 'General' },
      'remove curse':                    { recharge: 'General' },
      'remove disease':                  { recharge: 'General' },
      'remove fear':                     { recharge: 'General' },
      'remove paralysis':                { recharge: 'General' },
      'repel metal or stone':            { recharge: 'General' },
      'repel vermin':                    { recharge: '4 hours' },
      'repel wood':                      { recharge: 'General' },
      'repulsion':                       { recharge: 'General' },
      'resilient sphere':                { recharge: 'General' },
      'resistance':                      { recharge: '5 minutes' },
      'resist energy':                   { recharge: '1 hour' },
      'restoration':                     { recharge: 'General' },
      'resurrection':                    { recharge: 'General' },
      'reverse gravity':                 { recharge: 'General' },
      'righteous might':                 { recharge: '5 minutes' },
      'rope trick':                      { recharge: '6 hours' },
      'rusting grasp':                   { recharge: '5 minutes' },
      'sanctuary':                       { recharge: '5 minutes' },
      'scare':                           { recharge: 'General' },
      'scintillating pattern':           { recharge: 'General' },
      'scorching ray':                   { recharge: 'General' },
      'screen':                          { recharge: '24 hours' },
      'scrying':                         { recharge: 'General' },
      'sculpt sound':                    { recharge: '6 hours' },
      'searing light':                   { recharge: 'General' },
      'secret chest':                    { recharge: 'General' },
      'secret page':                     { recharge: '12 hours' },
      'secure shelter':                  { recharge: '12 hours' },
      'see invisibility':                { recharge: '4 hours' },
      'seeming':                         { recharge: '24 hours' },
      'sending':                         { recharge: 'General' },
      'sepia snake sigil':               { recharge: '24 hours' },
      'sequester':                       { recharge: '24 hours' },
      'shades':                          { recharge: 'General' },
      'shadow conjuration':              { recharge: 'General' },
      'shadow evocation':                { recharge: 'General' },
      'shadow walk':                     { recharge: '24 hours' },
      'shambler':                        { recharge: '24 hours' },
      'shapechange':                     { recharge: '4 hours' },
      'shatter':                         { recharge: 'General' },
      'shield':                          { recharge: '30 minutes' },
      'shield of faith':                 { recharge: '30 minutes' },
      'shield of law':                   { recharge: 'General' },
      'shield other':                    { recharge: '24 hours' },
      'shillelagh':                      { recharge: '30 minutes' },
      'shocking grasp':                  { recharge: 'General' },
      'shout':                           { recharge: 'General' },
      'shrink item':                     { recharge: '24 hours' },
      'silence':                         { recharge: '30 minutes' },
      'silent image':                    { recharge: 'General' },
      'simulacrum':                      { recharge: 'General' },
      'slay living':                     { recharge: 'General' },
      'sleep':                           { recharge: 'General' },
      'sleet storm':                     { recharge: 'General' },
      'slow':                            { recharge: 'General' },
      'snare':                           { recharge: '12 hours' },
      'soften earth and stone':          { recharge: '6 hours' },
      'solid fog':                       { recharge: 'General' },
      'song of discord':                 { recharge: 'General' },
      'soul bind':                       { recharge: 'General' },
      'sound burst':                     { recharge: 'General' },
      'speak with animals':              { recharge: '30 minutes' },
      'speak with dead':                 { recharge: '30 minutes' },
      'speak with plants':               { recharge: '30 minutes' },
      'spectral hand':                   { recharge: '30 minutes' },
      'spell immunity':                  { recharge: '1 hour' },
      'spell resistance':                { recharge: '30 minutes' },
      'spell turning':                   { recharge: '4 hours' },
      'spellstaff':                      { recharge: '24 hours' },
      'spider climb':                    { recharge: '1 hour' },
      'spike growth':                    { recharge: '6 hours' },
      'spike stones':                    { recharge: '6 hours' },
      'spiritual weapon':                { recharge: 'General' },
      'statue':                          { recharge: '6 hours' },
      'status':                          { recharge: '24 hours' },
      'stinking cloud':                  { recharge: 'General' },
      'stone shape':                     { recharge: '6 hours' },
      'stone tell':                      { recharge: '30 minutes' },
      'stone to flesh':                  { recharge: 'General' },
      'stoneskin':                       { recharge: 'General' },
      'storm of vengeance':              { recharge: 'General' },
      'suggestion':                      { recharge: '30 minutes' },
      'summon instrument':               { recharge: 'General' },
      'summon monster i':                { recharge: 'General' },
      'summon monster ii':               { recharge: 'General' },
      'summon monster iii':              { recharge: 'General' },
      'summon monster iv':               { recharge: 'General' },
      'summon monster v':                { recharge: 'General' },
      'summon monster vi':               { recharge: 'General' },
      'summon monster vii':              { recharge: 'General' },
      'summon monster viii':             { recharge: 'General' },
      'summon monster ix':               { recharge: 'General' },
      'summon nature\'s ally i':         { recharge: 'General' },
      'summon nature\'s ally ii':        { recharge: 'General' },
      'summon nature\'s ally iii':       { recharge: 'General' },
      'summon nature\'s ally iv':        { recharge: 'General' },
      'summon nature\'s ally v':         { recharge: 'General' },
      'summon nature\'s ally vi':        { recharge: 'General' },
      'summon nature\'s ally vii':       { recharge: 'General' },
      'summon nature\'s ally viii':      { recharge: 'General' },
      'summon nature\'s ally ix':        { recharge: 'General' },
      'summon swarm':                    { recharge: 'General' },
      'sunbeam':                         { recharge: 'General' },
      'sunburst':                        { recharge: 'General' },
      'surelife':                        { recharge: '30 minutes' },
      'symbol of death':                 { recharge: 'General' },
      'symbol of fear':                  { recharge: 'General' },
      'symbol of insanity':              { recharge: 'General' },
      'symbol of pain':                  { recharge: 'General' },
      'symbol of persuasion':            { recharge: 'General' },
      'symbol of sleep':                 { recharge: 'General' },
      'symbol of stunning':              { recharge: 'General' },
      'symbol of weakness':              { recharge: 'General' },
      'sympathetic vibration':           { recharge: '12 hours' },
      'sympathy':                        { recharge: 'General' },
      'telekinesis':                     { recharge: 'General' },
      'telekinetic sphere':              { recharge: 'General' },
      'telepathic bond':                 { recharge: '4 hours' },
      'teleport':                        { recharge: '4 hours' },
      'teleport object':                 { recharge: '4 hours' },
      'teleportation circle':            { recharge: 'General' },
      'temporal stasis':                 { recharge: 'General' },
      'time stop':                       { recharge: '4 hours' },
      'tiny hut':                        { recharge: '12 hours' },
      'tongues':                         { recharge: '1 hour' },
      'touch of fatigue':                { recharge: 'General' },
      'touch of idiocy':                 { recharge: 'General' },
      'touch of madness':                { recharge: 'General' },
      'transformation':                  { recharge: 'General' },
      'transmute metal to wood':         { recharge: '6 hours' },
      'transmute mud to rock':           { recharge: '6 hours' },
      'transmute rock to mud':           { recharge: '6 hours' },
      'transport via plants':            { recharge: '4 hours' },
      'trap the soul':                   { recharge: 'General' },
      'tree shape':                      { recharge: '24 hours' },
      'tree stride':                     { recharge: '24 hours' },
      'true creation':                   { recharge: 'General' },
      'true resurrection':               { recharge: 'General' },
      'true seeing':                     { recharge: 'General' },
      'true strike':                     { recharge: '5 minutes' },
      'undeath to death':                { recharge: 'General' },
      'undetectable alignment':          { recharge: '24 hours' },
      'unhallow':                        { recharge: 'General' },
      'unholy aura':                     { recharge: 'General' },
      'unholy blight':                   { recharge: 'General' },
      'unseen servant':                  { recharge: '6 hours' },
      'vampiric touch':                  { recharge: 'General' },
      'veil':                            { recharge: '12 hours' },
      'ventriloquism':                   { recharge: '5 minutes' },
      'virtue':                          { recharge: '5 minutes' },
      'vision':                          { recharge: '6 hours' },
      'wail of the banshee':             { recharge: 'General' },
      'wall of fire':                    { recharge: 'General' },
      'wall of force':                   { recharge: 'General' },
      'wall of ice':                     { recharge: 'General' },
      'wall of iron':                    { recharge: '12 hours' },
      'wall of stone':                   { recharge: '12 hours' },
      'wall of thorns':                  { recharge: 'General' },
      'warp wood':                       { recharge: '5 minutes' },
      'water breathing':                 { recharge: '4 hours' },
      'water walk':                      { recharge: '4 hours' },
      'waves of exhaustion':             { recharge: 'General' },
      'waves of fatigue':                { recharge: 'General' },
      'web':                             { recharge: '5 minutes' },
      'weird':                           { recharge: 'General' },
      'whirlwind':                       { recharge: 'General' },
      'whispering wind':                 { recharge: '30 minutes' },
      'wind walk':                       { recharge: '24 hours' },
      'wind wall':                       { recharge: 'General' },
      'wish':                            { recharge: 'General' },
      'wood shape':                      { recharge: '6 hours' },
      'word of chaos':                   { recharge: 'General' },
      'word of recall':                  { recharge: 'General' },
      'zone of silence':                 { recharge: '24 hours' },
      'zone of truth':                   { recharge: '30 minutes' },

      //RECHARGES
      //'': { recharge: 'General' },
    }
  };

//TODO The following still need to be converted into their own files
//  var dnd35 = {
//    all_source_texts: {
//      MH:      "Miniatures Handbook",
//      ToB:     "Tome of Battle",
//      BoED:    "Book of Exalted Deeds",
//      MoF:     "Magic of Faerun",
//      OA:      "Oriental Adventures",
//      unknown: "Unknown Text"
//    },
//    source_text_ToB: {
//      skills: { 'martial lore':             {base: 'martial lore',             attrib: '',                  default_ability_mod: 'int-mod', trained_only:true  } }
//    },
//    source_text_BoED: {
//      types: ['deathless']
//    },
//    source_text_MoF: {
//      spells: {
//        'acid splash': { resistance: 'Yes' },
//      }
//    },
//    source_text_OA: {
//      skills: { 'iaijutsu focus':           {base: 'iaijutsu focus',           attrib: '',                  default_ability_mod: 'cha-mod', trained_only:false } }
//    },
//    source_text_unknown: {
//      movement_modes: ['glide']
//    }
//  };

  // SECTION_ANCHOR
  // ███████╗ ██████╗██████╗ ██╗██████╗ ████████╗    ██╗███╗   ██╗██╗████████╗
  // ██╔════╝██╔════╝██╔══██╗██║██╔══██╗╚══██╔══╝    ██║████╗  ██║██║╚══██╔══╝
  // ███████╗██║     ██████╔╝██║██████╔╝   ██║       ██║██╔██╗ ██║██║   ██║
  // ╚════██║██║     ██╔══██╗██║██╔═══╝    ██║       ██║██║╚██╗██║██║   ██║
  // ███████║╚██████╗██║  ██║██║██║        ██║       ██║██║ ╚████║██║   ██║
  // ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝        ╚═╝       ╚═╝╚═╝  ╚═══╝╚═╝   ╚═╝

  var registerEventHandlers = function() {
    return;
  }; // registerEventHandlers

  var checkInstall = function() {
    if ((typeof state.skepickleCharacterSuiteImp === 'undefined') || (state.skepickleCharacterSuiteImp === null)) {
      state.skepickleCharacterSuiteImp = {};
    };
    if ((typeof state.skepickleCharacterSuiteImp.config === 'undefined') || (state.skepickleCharacterSuiteImp.config === null)) {
      state.skepickleCharacterSuiteImp.config = {};
    };
    if ((typeof state.skepickleCharacterSuiteImp.config.SourceTexts === 'undefined') || (state.skepickleCharacterSuiteImp.config.SourceTexts === null) || (state.skepickleCharacterSuiteImp.config.SourceTexts === '')) {
      state.skepickleCharacterSuiteImp.config.SourceTexts = 'UA';
    } else {
      let a = state.skepickleCharacterSuiteImp.config.SourceTexts.split(',');
      let b = [];
      for (let i=0; i<a.length; i++) {
        let p; try { p = eval('skepickleCharacterSuite_'+a[i]); } catch (e) { p = null; };
        if ((typeof p !== 'undefined') && (p !== null) &&
            (typeof p.source_text !== 'undefined') && (p.source_text !== null)) {
          b.push(a[i]);
        };
      };
      if (!(b.includes('UA'))) {
        b.push('UA');
      };
      state.skepickleCharacterSuiteImp.config.SourceTexts = b.join(',');
    };

    log("########## skepickleCharacterSuite_UA");
  }; // checkInstall

  var initialize = function() {
    return;
  }; // initialize

  return {
    // Make the following functions available outside the local namespace
    CheckInstall: checkInstall,
    RegisterEventHandlers: registerEventHandlers,
    Initialize: initialize
  };

}());

on("ready", function() {
  skepickleCharacterSuite_UA.CheckInstall();
  skepickleCharacterSuite_UA.Initialize();
  skepickleCharacterSuite_UA.RegisterEventHandlers();
});
